// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"marmota/server/data/ent/nodemetadata"
	"marmota/server/data/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NodeMetadataQuery is the builder for querying NodeMetadata entities.
type NodeMetadataQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.NodeMetadata
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NodeMetadataQuery builder.
func (nmq *NodeMetadataQuery) Where(ps ...predicate.NodeMetadata) *NodeMetadataQuery {
	nmq.predicates = append(nmq.predicates, ps...)
	return nmq
}

// Limit adds a limit step to the query.
func (nmq *NodeMetadataQuery) Limit(limit int) *NodeMetadataQuery {
	nmq.limit = &limit
	return nmq
}

// Offset adds an offset step to the query.
func (nmq *NodeMetadataQuery) Offset(offset int) *NodeMetadataQuery {
	nmq.offset = &offset
	return nmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nmq *NodeMetadataQuery) Unique(unique bool) *NodeMetadataQuery {
	nmq.unique = &unique
	return nmq
}

// Order adds an order step to the query.
func (nmq *NodeMetadataQuery) Order(o ...OrderFunc) *NodeMetadataQuery {
	nmq.order = append(nmq.order, o...)
	return nmq
}

// First returns the first NodeMetadata entity from the query.
// Returns a *NotFoundError when no NodeMetadata was found.
func (nmq *NodeMetadataQuery) First(ctx context.Context) (*NodeMetadata, error) {
	nodes, err := nmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nodemetadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nmq *NodeMetadataQuery) FirstX(ctx context.Context) *NodeMetadata {
	node, err := nmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NodeMetadata ID from the query.
// Returns a *NotFoundError when no NodeMetadata ID was found.
func (nmq *NodeMetadataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nodemetadata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nmq *NodeMetadataQuery) FirstIDX(ctx context.Context) int {
	id, err := nmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NodeMetadata entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one NodeMetadata entity is not found.
// Returns a *NotFoundError when no NodeMetadata entities are found.
func (nmq *NodeMetadataQuery) Only(ctx context.Context) (*NodeMetadata, error) {
	nodes, err := nmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nodemetadata.Label}
	default:
		return nil, &NotSingularError{nodemetadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nmq *NodeMetadataQuery) OnlyX(ctx context.Context) *NodeMetadata {
	node, err := nmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NodeMetadata ID in the query.
// Returns a *NotSingularError when exactly one NodeMetadata ID is not found.
// Returns a *NotFoundError when no entities are found.
func (nmq *NodeMetadataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = &NotSingularError{nodemetadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nmq *NodeMetadataQuery) OnlyIDX(ctx context.Context) int {
	id, err := nmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NodeMetadataSlice.
func (nmq *NodeMetadataQuery) All(ctx context.Context) ([]*NodeMetadata, error) {
	if err := nmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return nmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (nmq *NodeMetadataQuery) AllX(ctx context.Context) []*NodeMetadata {
	nodes, err := nmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NodeMetadata IDs.
func (nmq *NodeMetadataQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := nmq.Select(nodemetadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nmq *NodeMetadataQuery) IDsX(ctx context.Context) []int {
	ids, err := nmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nmq *NodeMetadataQuery) Count(ctx context.Context) (int, error) {
	if err := nmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return nmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (nmq *NodeMetadataQuery) CountX(ctx context.Context) int {
	count, err := nmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nmq *NodeMetadataQuery) Exist(ctx context.Context) (bool, error) {
	if err := nmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return nmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (nmq *NodeMetadataQuery) ExistX(ctx context.Context) bool {
	exist, err := nmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NodeMetadataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nmq *NodeMetadataQuery) Clone() *NodeMetadataQuery {
	if nmq == nil {
		return nil
	}
	return &NodeMetadataQuery{
		config:     nmq.config,
		limit:      nmq.limit,
		offset:     nmq.offset,
		order:      append([]OrderFunc{}, nmq.order...),
		predicates: append([]predicate.NodeMetadata{}, nmq.predicates...),
		// clone intermediate query.
		sql:  nmq.sql.Clone(),
		path: nmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (nmq *NodeMetadataQuery) GroupBy(field string, fields ...string) *NodeMetadataGroupBy {
	group := &NodeMetadataGroupBy{config: nmq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := nmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return nmq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (nmq *NodeMetadataQuery) Select(field string, fields ...string) *NodeMetadataSelect {
	nmq.fields = append([]string{field}, fields...)
	return &NodeMetadataSelect{NodeMetadataQuery: nmq}
}

func (nmq *NodeMetadataQuery) prepareQuery(ctx context.Context) error {
	for _, f := range nmq.fields {
		if !nodemetadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nmq.path != nil {
		prev, err := nmq.path(ctx)
		if err != nil {
			return err
		}
		nmq.sql = prev
	}
	return nil
}

func (nmq *NodeMetadataQuery) sqlAll(ctx context.Context) ([]*NodeMetadata, error) {
	var (
		nodes = []*NodeMetadata{}
		_spec = nmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &NodeMetadata{config: nmq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, nmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (nmq *NodeMetadataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nmq.querySpec()
	return sqlgraph.CountNodes(ctx, nmq.driver, _spec)
}

func (nmq *NodeMetadataQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := nmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (nmq *NodeMetadataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   nodemetadata.Table,
			Columns: nodemetadata.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nodemetadata.FieldID,
			},
		},
		From:   nmq.sql,
		Unique: true,
	}
	if unique := nmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := nmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nodemetadata.FieldID)
		for i := range fields {
			if fields[i] != nodemetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nmq *NodeMetadataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nmq.driver.Dialect())
	t1 := builder.Table(nodemetadata.Table)
	selector := builder.Select(t1.Columns(nodemetadata.Columns...)...).From(t1)
	if nmq.sql != nil {
		selector = nmq.sql
		selector.Select(selector.Columns(nodemetadata.Columns...)...)
	}
	for _, p := range nmq.predicates {
		p(selector)
	}
	for _, p := range nmq.order {
		p(selector)
	}
	if offset := nmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NodeMetadataGroupBy is the group-by builder for NodeMetadata entities.
type NodeMetadataGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nmgb *NodeMetadataGroupBy) Aggregate(fns ...AggregateFunc) *NodeMetadataGroupBy {
	nmgb.fns = append(nmgb.fns, fns...)
	return nmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (nmgb *NodeMetadataGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := nmgb.path(ctx)
	if err != nil {
		return err
	}
	nmgb.sql = query
	return nmgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := nmgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (nmgb *NodeMetadataGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(nmgb.fields) > 1 {
		return nil, errors.New("ent: NodeMetadataGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := nmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) StringsX(ctx context.Context) []string {
	v, err := nmgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nmgb *NodeMetadataGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nmgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = fmt.Errorf("ent: NodeMetadataGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) StringX(ctx context.Context) string {
	v, err := nmgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (nmgb *NodeMetadataGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(nmgb.fields) > 1 {
		return nil, errors.New("ent: NodeMetadataGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := nmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) IntsX(ctx context.Context) []int {
	v, err := nmgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nmgb *NodeMetadataGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nmgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = fmt.Errorf("ent: NodeMetadataGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) IntX(ctx context.Context) int {
	v, err := nmgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (nmgb *NodeMetadataGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(nmgb.fields) > 1 {
		return nil, errors.New("ent: NodeMetadataGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := nmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := nmgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nmgb *NodeMetadataGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nmgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = fmt.Errorf("ent: NodeMetadataGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) Float64X(ctx context.Context) float64 {
	v, err := nmgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (nmgb *NodeMetadataGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(nmgb.fields) > 1 {
		return nil, errors.New("ent: NodeMetadataGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := nmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := nmgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (nmgb *NodeMetadataGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nmgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = fmt.Errorf("ent: NodeMetadataGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nmgb *NodeMetadataGroupBy) BoolX(ctx context.Context) bool {
	v, err := nmgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nmgb *NodeMetadataGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range nmgb.fields {
		if !nodemetadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := nmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (nmgb *NodeMetadataGroupBy) sqlQuery() *sql.Selector {
	selector := nmgb.sql
	columns := make([]string, 0, len(nmgb.fields)+len(nmgb.fns))
	columns = append(columns, nmgb.fields...)
	for _, fn := range nmgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(nmgb.fields...)
}

// NodeMetadataSelect is the builder for selecting fields of NodeMetadata entities.
type NodeMetadataSelect struct {
	*NodeMetadataQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (nms *NodeMetadataSelect) Scan(ctx context.Context, v interface{}) error {
	if err := nms.prepareQuery(ctx); err != nil {
		return err
	}
	nms.sql = nms.NodeMetadataQuery.sqlQuery(ctx)
	return nms.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nms *NodeMetadataSelect) ScanX(ctx context.Context, v interface{}) {
	if err := nms.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (nms *NodeMetadataSelect) Strings(ctx context.Context) ([]string, error) {
	if len(nms.fields) > 1 {
		return nil, errors.New("ent: NodeMetadataSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := nms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nms *NodeMetadataSelect) StringsX(ctx context.Context) []string {
	v, err := nms.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (nms *NodeMetadataSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nms.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = fmt.Errorf("ent: NodeMetadataSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nms *NodeMetadataSelect) StringX(ctx context.Context) string {
	v, err := nms.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (nms *NodeMetadataSelect) Ints(ctx context.Context) ([]int, error) {
	if len(nms.fields) > 1 {
		return nil, errors.New("ent: NodeMetadataSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := nms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nms *NodeMetadataSelect) IntsX(ctx context.Context) []int {
	v, err := nms.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (nms *NodeMetadataSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nms.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = fmt.Errorf("ent: NodeMetadataSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nms *NodeMetadataSelect) IntX(ctx context.Context) int {
	v, err := nms.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (nms *NodeMetadataSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(nms.fields) > 1 {
		return nil, errors.New("ent: NodeMetadataSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := nms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nms *NodeMetadataSelect) Float64sX(ctx context.Context) []float64 {
	v, err := nms.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (nms *NodeMetadataSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nms.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = fmt.Errorf("ent: NodeMetadataSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nms *NodeMetadataSelect) Float64X(ctx context.Context) float64 {
	v, err := nms.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (nms *NodeMetadataSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(nms.fields) > 1 {
		return nil, errors.New("ent: NodeMetadataSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := nms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nms *NodeMetadataSelect) BoolsX(ctx context.Context) []bool {
	v, err := nms.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (nms *NodeMetadataSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nms.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodemetadata.Label}
	default:
		err = fmt.Errorf("ent: NodeMetadataSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nms *NodeMetadataSelect) BoolX(ctx context.Context) bool {
	v, err := nms.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nms *NodeMetadataSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := nms.sqlQuery().Query()
	if err := nms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (nms *NodeMetadataSelect) sqlQuery() sql.Querier {
	selector := nms.sql
	selector.Select(selector.Columns(nms.fields...)...)
	return selector
}
