// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"marmota/server/data/ent/nodemetadata"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// NodeMetadata is the model entity for the NodeMetadata schema.
type NodeMetadata struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NodeMetadata) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case nodemetadata.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type NodeMetadata", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NodeMetadata fields.
func (nm *NodeMetadata) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nodemetadata.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			nm.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this NodeMetadata.
// Note that you need to call NodeMetadata.Unwrap() before calling this method if this NodeMetadata
// was returned from a transaction, and the transaction was committed or rolled back.
func (nm *NodeMetadata) Update() *NodeMetadataUpdateOne {
	return (&NodeMetadataClient{config: nm.config}).UpdateOne(nm)
}

// Unwrap unwraps the NodeMetadata entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (nm *NodeMetadata) Unwrap() *NodeMetadata {
	tx, ok := nm.config.driver.(*txDriver)
	if !ok {
		panic("ent: NodeMetadata is not a transactional entity")
	}
	nm.config.driver = tx.drv
	return nm
}

// String implements the fmt.Stringer.
func (nm *NodeMetadata) String() string {
	var builder strings.Builder
	builder.WriteString("NodeMetadata(")
	builder.WriteString(fmt.Sprintf("id=%v", nm.ID))
	builder.WriteByte(')')
	return builder.String()
}

// NodeMetadataSlice is a parsable slice of NodeMetadata.
type NodeMetadataSlice []*NodeMetadata

func (nm NodeMetadataSlice) config(cfg config) {
	for _i := range nm {
		nm[_i].config = cfg
	}
}
