// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"marmota/server/data/ent/nodemetadata"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NodeMetadataCreate is the builder for creating a NodeMetadata entity.
type NodeMetadataCreate struct {
	config
	mutation *NodeMetadataMutation
	hooks    []Hook
}

// Mutation returns the NodeMetadataMutation object of the builder.
func (nmc *NodeMetadataCreate) Mutation() *NodeMetadataMutation {
	return nmc.mutation
}

// Save creates the NodeMetadata in the database.
func (nmc *NodeMetadataCreate) Save(ctx context.Context) (*NodeMetadata, error) {
	var (
		err  error
		node *NodeMetadata
	)
	if len(nmc.hooks) == 0 {
		if err = nmc.check(); err != nil {
			return nil, err
		}
		node, err = nmc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NodeMetadataMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nmc.check(); err != nil {
				return nil, err
			}
			nmc.mutation = mutation
			node, err = nmc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nmc.hooks) - 1; i >= 0; i-- {
			mut = nmc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nmc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (nmc *NodeMetadataCreate) SaveX(ctx context.Context) *NodeMetadata {
	v, err := nmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (nmc *NodeMetadataCreate) check() error {
	return nil
}

func (nmc *NodeMetadataCreate) sqlSave(ctx context.Context) (*NodeMetadata, error) {
	_node, _spec := nmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nmc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (nmc *NodeMetadataCreate) createSpec() (*NodeMetadata, *sqlgraph.CreateSpec) {
	var (
		_node = &NodeMetadata{config: nmc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: nodemetadata.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nodemetadata.FieldID,
			},
		}
	)
	return _node, _spec
}

// NodeMetadataCreateBulk is the builder for creating many NodeMetadata entities in bulk.
type NodeMetadataCreateBulk struct {
	config
	builders []*NodeMetadataCreate
}

// Save creates the NodeMetadata entities in the database.
func (nmcb *NodeMetadataCreateBulk) Save(ctx context.Context) ([]*NodeMetadata, error) {
	specs := make([]*sqlgraph.CreateSpec, len(nmcb.builders))
	nodes := make([]*NodeMetadata, len(nmcb.builders))
	mutators := make([]Mutator, len(nmcb.builders))
	for i := range nmcb.builders {
		func(i int, root context.Context) {
			builder := nmcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeMetadataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nmcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nmcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nmcb *NodeMetadataCreateBulk) SaveX(ctx context.Context) []*NodeMetadata {
	v, err := nmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
